import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DbInitializer } from "@/components/DbInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthCheck } from '@/components/auth/AuthCheck';
import { SyncWrapper } from '@/components/SyncWrapper';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--color-bg-primary)] text-[var(--color-text-primary)]`}
      >
        <DbInitializer />
        <AuthCheck>
          <SyncWrapper>
            {children}
          </SyncWrapper>
        </AuthCheck>
      </body>
    </html>
  );
}
